const WA="917084144501";
const DATA={
"Poster Design":{cat:"design",i:"P",d:"Advertisement, promotional, event, educational and social media posters.",p:"₹29–₹199",f:[["type","Poster Type","select","Advertisement|Promotional|Event|Educational|Festival|Social Media|Other"],["size","Size","select","A4|A3|A5|Instagram Post|Instagram Story|WhatsApp|Custom"],["orientation","Orientation","select","Portrait|Landscape|Square"],["theme","Theme / Style","select","Premium|Modern|Minimal|Creative|Corporate|Traditional"],["colours","Preferred Colours","input","e.g. Navy & Gold"],["heading","Main Heading","input","Exact headline"],["content","Complete Poster Content","textarea","All text to appear on the poster"]]},
"Logo Design":{cat:"design business",i:"L",d:"Professional logos, monograms, icons and simple brand identity work.",p:"₹99–₹199",f:[["category","Business / Industry","input","e.g. Education, Food, Clothing"],["tagline","Tagline","input","If applicable"],["logoType","Logo Type","select","Text|Icon|Icon + Text|Monogram"],["style","Preferred Style","select","Minimal|Modern|Luxury|Professional|Creative|Traditional"],["colours","Preferred Colours","input",""],["avoid","Colours / Styles to Avoid","input","Optional"],["symbol","Symbol / Icon Idea","textarea","What should the logo communicate?"],["usage","Main Usage","input","Website, shop, packaging, social media, etc."]]},
"Visiting Card":{cat:"design business",i:"V",d:"Personal and business cards for print or digital use.",p:"₹49–₹149",f:[["person","Person Name","input","Full name"],["designation","Designation","input","Founder, Manager, etc."],["phone2","Phone / WhatsApp","input","Number to display"],["email2","Email","input",""],["address","Address","textarea","Business or office address"],["website","Website / Social Handles","input","Optional"],["side","Card Side","select","Single Side|Double Side"],["qr","QR Code","select","No|Yes — provide destination"]]},
"Photo Editing":{cat:"design",i:"E",d:"Background removal, retouching, enhancement, colour correction and creative edits.",p:"₹49–₹199",f:[["editType","Editing Required","select","Background Remove|Retouching|Enhancement|Color Correction|Creative Edit|Other"],["output","Required Output","select","JPG|PNG|Transparent PNG|Other"],["look","Desired Look","input","Natural, premium, dramatic, clean, etc."],["count","Number of Photos","input","Approx. quantity"],["details","Editing Details","textarea","Describe exactly what should be changed"]]},
"PPT / Presentation":{cat:"design documents",i:"P",d:"Professional presentations for school, business, projects and events.",p:"₹29–₹199",f:[["topic","Presentation Topic","input",""],["slides","Approx. Number of Slides","input","e.g. 10"],["purpose","Purpose / Audience","input","School, business, pitch, event, etc."],["ratio","Slide Ratio","select","16:9 Widescreen|4:3 Standard"],["content","Content Available","select","I will provide content|Need content arrangement only|Need full slide structuring"],["style","Presentation Style","select","Academic|Corporate|Premium|Minimal|Creative"],["notes","Charts / Images / Special Elements","textarea","Optional"]]},
"Event / Invitation":{cat:"design",i:"E",d:"Invitations, event posters, announcements and digital cards.",p:"₹49–₹199",f:[["event","Event Name","input",""],["date","Date","input",""],["time","Time","input",""],["venue","Venue","input",""],["host","Host / Organiser","input",""],["guests","Chief Guest / Speakers","textarea","Optional"],["format","Format","select","Poster|Invitation|Digital Card|Social Media"],["theme","Theme","select","Premium|Modern|Traditional|Minimal|Festive|Creative"]]},
"Typing & PDF":{cat:"documents",i:"T",d:"Typing, formatting, PDF creation, conversion and document cleanup.",p:"₹29–₹149",f:[["source","Source Material","select","Image|Scanned PDF|Handwritten|Existing Document|Other"],["language","Language","select","English|Hindi|Both"],["pages","Approx. Pages","input",""],["format","Final Format","select","Word|PDF|Both"],["formatting","Formatting Required","select","Basic|Professional|Tables & Layout|No special formatting"],["details","Special Requirements","textarea",""]]},
"Data Entry":{cat:"documents business",i:"D",d:"Structured data entry, Excel/Sheets work and clean formatting.",p:"₹49–₹199",f:[["source","Data Source","select","PDF|Images|Excel|Google Sheets|Handwritten|Other"],["language","Language","select","English|Hindi|Both"],["records","Approx. Records / Rows","input",""],["output","Required Output","select","Excel|Google Sheets|Word|CSV|Other"],["formatting","Formatting / Sorting","select","Basic Entry|Formatting|Sorting & Filtering|Advanced Structure"],["details","Data Entry Instructions","textarea","Explain the task and columns required"]]}
};
const service=document.getElementById("service"),dynamic=document.getElementById("dynamic"),grid=document.getElementById("servicesGrid");
Object.keys(DATA).forEach(s=>service.add(new Option(s,s)));
function makeFields(){const x=DATA[service.value];dynamic.innerHTML='<h3>03 — '+service.value.toUpperCase()+' REQUIREMENTS</h3><div class="dynamic">'+x.f.map(([n,l,t,p])=>t==="select"?`<label>${l}<select name="req_${n}">${p.split("|").map(v=>`<option>${v}</option>`).join("")}</select></label>`:t==="textarea"?`<label class="full">${l}<textarea name="req_${n}" placeholder="${p}"></textarea></label>`:`<label>${l}<input name="req_${n}" placeholder="${p}"></label>`).join("")+'</div>'}
service.onchange=makeFields;makeFields();
Object.entries(DATA).forEach(([name,x])=>{const a=document.createElement("article");a.className="card";a.dataset.cat=x.cat;a.innerHTML=`<div class="icon">${x.i}</div><div class="meta">EDH • DIGITAL SERVICE</div><h3>${name}</h3><p>${x.d}</p><div class="price">${x.p}</div><button type="button" data-s="${name}">DESIGN / ORDER NOW →</button>`;grid.appendChild(a)});

document.querySelectorAll(".filter").forEach(btn=>btn.addEventListener("click",()=>{document.querySelectorAll(".filter").forEach(b=>b.classList.remove("active"));btn.classList.add("active");const f=btn.dataset.filter;document.querySelectorAll(".card").forEach(c=>{c.classList.toggle("hidden",f!=="all"&&!c.dataset.cat.split(" ").includes(f))})}));
grid.addEventListener("click",e=>{if(!e.target.dataset.s)return;const s=e.target.dataset.s;const text=`Hello RL-33 / EDH, I came through the RL-33 Digital Services catalogue. I want to order ${s}. Please share the next steps and confirm the final price and delivery time for my requirement.`;location.href=`https://wa.me/${WA}?text=${encodeURIComponent(text)}`});

const samples=[["samples/edh-poster-sample-01.png","Poster Design","Promotional sample"],["samples/poster-01.svg","Poster Design","Visual hierarchy"],["samples/poster-02.svg","Event Poster","Event communication"],["samples/logo-01.svg","Logo Design","Brand identity"],["samples/visiting-card-01.svg","Visiting Card","Business identity"],["samples/ppt-01.svg","PPT / Presentation","Slide design"],["samples/event-01.svg","Event / Invitation","Digital event"],["samples/photo-edit-01.svg","Photo Editing","Visual enhancement"],["samples/typing-01.svg","Typing & PDF","Document work"],["samples/data-entry-01.svg","Data Entry","Structured data"]];
const pg=document.getElementById("portfolioGrid");samples.forEach(([im,t,s])=>{const a=document.createElement("article");a.className="p-card";a.innerHTML=`<img loading="lazy" src="${im}" alt="${t} sample"><div class="p-cap"><b>${t}</b><span>${s} • EDH</span></div>`;pg.appendChild(a)});

document.getElementById("form").addEventListener("submit",e=>{e.preventDefault();const f=new FormData(e.target),s=f.get("service"),x=DATA[s],lines=["*RL-33 × EDH — SERVICE APPLICATION*","",`*Service:* ${s}`,`*Client Name:* ${f.get("name")}`,`*Business / Organisation:* ${f.get("business")||"N/A"}`,`*WhatsApp / Phone:* ${f.get("phone")}`,`*Email:* ${f.get("email")||"N/A"}`];x.f.forEach(([n,l])=>{const v=f.get("req_"+n);if(v)lines.push(`*${l}:* ${v}`)});lines.push(`*Required By:* ${f.get("deadline")||"Not specified"}`,`*Reference:* ${f.get("reference")||"None"}`,`*Additional Instructions:* ${f.get("extra")||"None"}` ,"","I came through the RL-33 Digital Services / EDH page. Please review my requirement and contact me.");location.href=`https://wa.me/${WA}?text=${encodeURIComponent(lines.join("\n"))}`});

document.getElementById("menu").onclick=()=>document.getElementById("nav").classList.toggle("open");
